### ISSUE TITLE
Fail to create quad mesh for many holes

### ISSUE THREAD

**Issue by TangLaoya** [DanielZint/RatRace#1]
Dear Prof. DanielZint,

Thank you for providing so powerful quad mesher RatRace. I tested it with some simple shapes and it works well. However, when I tested it with a shape with many holes, it failed to create correct quad mesh. Could you please help me to take a look at it?

Thanks,
Tang Laoya

[transition4to1.off.gz](https://github.com/DanielZint/RatRace/files/8094563/transition4to1.off.gz)

**Comment by daniel-zint** [comment]
Dear Tang Laoya,

The mesh you sent is indeed a tough one. The good news is, I could generate a quad mesh on it. The bad news is, there are low quality quads, which might be a problem for you.

One thing that you should keep in mind when you use the code is that it uses a cache (see the 'cache' folder in the project that is generated when running the code for the first time). If you use the same name for a different mesh it will use the cached information for the mesh generation. Therefore, you should have unique names for your meshes.

My quality output for your mesh looks like this:
    qMin = 0
    qMean = 0.756099
    Quality 0 - 0.1        |       11
    Quality 0.1 - 0.2      |       4
    Quality 0.2 - 0.3      |       5
    Quality 0.3 - 0.4      |       74
    Quality 0.4 - 0.5      |       281
    Quality 0.5 - 0.6      |       7992
    Quality 0.6 - 0.7      |       73000
    Quality 0.7 - 0.8      |       114009
    Quality 0.8 - 0.9      |       33665
    Quality 0.9 - 1        |       34065
    Valences: 32124 < 4 | 102223 == 4 | 31477 > 4
    singular vertices [%]: 38.3545

Again, there is at least one degenerated quad with quality of 0. I just checked and the problem is that Blossom-Quad already generates qMin=0. That means the degenerated quad appears somewhere on the boundary. Unfortunately, I cannot give you any post processing step to resolve that issue. I am pretty sure it is possible but I would have to take a much closer look to figure something out.

If your goal is just to produce a valid quad mesh, that can be achieved by generating a hybrid mesh and then subdividing it. Here is a modified main.cpp where a subdivision is used instead of triangle merging or blossom quad: 
[main.zip](https://github.com/DanielZint/RatRace/files/8096113/main.zip)
Nevertheless, you should be aware that this method produces much more quads than the others.

I hope this helps you somehow. If you have further questions, don't hesitate to ask me.


Best regards,
Daniel Zint

P.S.: I am not a professor so no need  for that formality ;-)

**Comment by TangLaoya** [comment]
Dear Daniel,
Thank you very much for your kindly reply. Yes, the simplest method is to subdivide triangles, but as you said, it will generate much more quads. I am also seeking for less quads with good quality. 
In fact, I am trying to implement the algorithm by this paper:
https://cims.nyu.edu/~ag6961/GIULIANI_quad.pdf

But I am failed in the 'edge coloring' algorithm. I can't let one color removed from the boundary edges if number boundary edges is even. Do you have any good suggestion?

In addition, the idea in your paper is excellent. You use blossom to generate quad at boundary, and then user your fast method to generate meshes inside. My question is: how do you control the blossom to let it just generate quad for the triangles near boundaries?

Thanks,
Tang Laoya

**Comment by daniel-zint** [comment]
The thing with the method you sent is, that it also will not solve your problem. As they state, they work similar to Blossom-Quad by removing edges. But Blossom-Quad already gives the optimal solution. In other words, if Blossom-Quad cannot create a good mesh, the method of Giuliani and Krivodonova will also not be able to do it.

I guess your best chance is to find the quads with low quality and apply some post-processing step to them. I already added a set of post-processing steps to my code but there are cases that are not covered.

Another option would be to have a look at cross-field methods. Something like that might be of interest for you:
[Frame fields: Anisotropic and non-orthogonal cross fields](https://nyuscholars.nyu.edu/en/publications/frame-fields-anisotropic-and-non-orthogonal-cross-fields)

**Comment by daniel-zint** [comment]
For your question on how I distinguish between boundary and interior:
I perform a coloring on the vertices around each boundary to find a ring of two triangle layers for every boundary. Then I make sure that all boundary regions have an even number of triangles.

There are a few more steps in between. It is all explained in the paper. If you don't have access to it and want to read it, just let me know then I can send you a pre-print.

**Comment by TangLaoya** [comment]
Dear Daniel,
Thank you very much for your kindly reply. I have got a copy of your paper. I need to further study and try to understand everything you said in your paper. I will also study the 'cross-field methods' you mentioned.

BTW: could you please also provide a CPU version of your RatRace? I tried to modify your code to let it work on CPU configure since there is no GPU card on the computer, maybe there is some error in my modified code. 

Thanks,
Tang Laoya

**Comment by daniel-zint** [comment]
Hey,
the part that is CUDA Code is just the smoothing step in the post-processing. The method is called Discrete Mesh Optimization (DMO). Luckily, I wrote a version of it that also runs on CPU so yes, I can provide a RatRace Version that is CPU only. But I don't know when I will find the time to do so. I will try next week but there is a lot going on. I will let you know when I managed to update the code.

**Comment by TangLaoya** [comment]
Dear Daniel,
Thank you very much for your kindly reply. This weekend I tried to study the 'cross-field methods' you mentioned, but I still don't know what it can help me in my structure.

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Dear Daniel,
Thank you very much for your kindly reply. This weekend I tried to study the 'cross-field methods' you mentioned, but I still don't know what it can help me in my structure.

Thanks,
Tang Laoya

**Comment by daniel-zint** [comment]
My knowledge on cross-field methods is also rather restricted. People often show beautiful results in their cross-field based methods but I don't know if there is any open source project that you could use to generate some quad mesh. Implementing them yourself is quite tough.

I won't be able to update the RatRace code this week. Next week I should have more time.

**Comment by TangLaoya** [comment]
Dear Daniel,
Thank you very much for your kindly reply. Yes just as you said, it is too difficult for me to study the cross-field method:(
I only need to generate quad mesh by converting the triangles into quads. I also require that boundary nodes don't change (if number of boundary nodes is odd, I will split the boundary triangle with maximal boundary edge length). Therefore, your hybrid method is best for me.

Thanks,
Tang Laoya

**Comment by daniel-zint** [comment]
Hi,
I finally found some time to add the templated version of DMO to the code. It is added as a submodule so be aware that you need to clone the Git repository now with --recurse.
I could not check if the code runs on a machine without Cuda installed but as DMO does, I don't see a reason why this project should not. However, it might be that I made some mistake. In that case, please let me know.

Best regards,
Daniel

**Comment by TangLaoya** [comment]
Dear Daniel,

Thank you very much for your kindly update. Yes, the latest code works. For some simple models it can generate very beautiful quad meshes. However, for the one that I uploaded the first time, it still can't generate final quad mesh. The following message displayed:

done [0.000 secs]. 0 grows, 0 expands, 0 shrinks
    expands: [0.000 secs], shrinks: [0.000 secs], dual updates: [0.000 secs]
perfect matching with 0 nodes and 0 edges
    starting init...done [0.000 secs]. 0 trees
    .
done [0.000 secs]. 0 grows, 0 expands, 0 shrinks
    expands: [0.000 secs], shrinks: [0.000 secs], dual updates: [0.000 secs]
I20220413 07:36:06.449043 138236 RatRace.cpp:322] Greedy triangle merge on interior
I20220413 07:36:07.304776 138236 main.cpp:144] Start RatRace
I20220413 07:36:07.369886 138236 RatRace.cpp:332] Number of triangles = 64
I20220413 07:36:07.818861 138236 main.cpp:151] Finish RatRace
I20220413 07:36:08.635948 138236 SizeGrid.h:46] Read SizeGrid from cache file 'E:\company\mesh\quadmesh\RatRace\RatRace-main\cache\transition4to1_SizeGrid_1000_1000_float.bin'
I20220413 07:36:08.657505 138236 RatRace.cpp:350] Removed interior val2: 394
I20220413 07:36:08.691980 138236 RatRace.cpp:353] Splitted boundary val2: 29
I20220413 07:36:08.714291 138236 RatRace.cpp:354] Removed boundary val2: 8
I20220413 07:36:08.738458 138236 RatRace.cpp:355] Removed boundary val2: 0


Could you please help me to take a look at it?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
The code break down in function optimizeHierarchical:

The error message is below:
Run-Time Check Failure #2 - Stack around the variable 'oneRing' was corrupted.

**Comment by TangLaoya** [comment]
Dear Daniel,

The crash problem is solved after simply changed MAX_ONE_RING_SIZE from 16 to 200. However, the output mesh is not correct. For example, the section I put here contain a large triangle with it's one edge overlapped with several boundaries. Could you please help me to take a look at it?
![1649809363(1)](https://user-images.githubusercontent.com/3899608/163075343-9a9e2013-e8e7-4573-a838-5b2250647e55.png)

Thanks,
Tang Laoya

**Comment by daniel-zint** [comment]
> The code break down in function optimizeHierarchical:
> 
> The error message is below: Run-Time Check Failure #2 - Stack around the variable 'oneRing' was corrupted.

I added a warning to the DMO code that tells the user that MAX_ONE_RING_SIZE might be too small. However, you don't need to increase it to 200. I think when you go to 32 you should be larger than any reasonable configuration. Actually, 16 is already a really big value. If your mesh has vertices with more than 16 neighbors, then the output is usually of low quality.

I also tried to check how the mesh quality can be improved but I cannot give you any fast answer to that. One thing I noticed is that your input mesh is not really good for making it a quad mesh. You could try to improve the quality of the triangle mesh and that might then also give a better quad mesh. Otherwise, I am afraid that I am not able to help you. Sorry!
